sudo: false
language: node_js
node_js:
- '10'
install: false
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
script: travis_wait make travis
deploy:
- provider: script
  skip_cleanup: true
  script: npm run coverage
  on:
    branch: master
env:
  global:
    - secure: u1wXTK16Y3wgiKmoXBhxeoCeXKY/5Cj9UtuZay+mAjSRRXqzJXqn4eGwTwAZ38rFJxq5tPd7HhjNfVnprOVZUzZ2tSUeGXszkDlwUthPHvhniV7tSe4I4Dmcesru3/ru7ktuLf6hskEwe14RV19Ax4Ey9CkqlM0wCYothqLgPow3BsIJG1Hw4xTL4zFSjIHwkmz/8xkD+5wtgT4Tq2DemqnOQBwTam+i2xkG4zb7WwtmcXUXNtXjST1zOKbZ1oIlAkpiSEOWQiawj3vtApzAhG80zBRjrJB6c+gWF1qjPVW7+cMv0drzlIb1fYipr5lqYfKCyZIONOcdOMBe22O/qrl+An83weQ09Vr/JMRnf/2kdO5GCX377lI8VpRK+3yPAXX3VNQfPXSKAUawF7qXI7KesEdr4qIgeaFlhhegYKntzhZ71j4RguP711jfVPk2bCLGy7jmBx4eip4Bwt93EZCHpS91608RWzfgeW4sGg3DxWnTvobwSuIfiR9cAZ308N/uRHyZ3ig0mQ97x5zAGTpX0+ctekQsABC9VGXDE1UsOs76j4ibyb+sHfY1HGRUVKfQm+9/4OzLlR7tZuxS+Ltedrufu9GMxTnkH45ORQfb92K5nccyJDpzw/EwKQWD80HKstSAtro++zgMhCeTVMD3ShmfzvwCD7iotJpGjNg=
    - secure: YN8CbVHgIyPyFrfGgiZpr7nPz4trg7RucnRuFndr6haYSQgJijP+g3jj8u6J5a5cYC4A8l30L97GghDszMUWbaG7G6yD/FKplPrRK3pdtl9nH8gsdjrYoPlvILrx5jI5GVz0V8QMIMPqogcBfCGzRVWFYt976EIy5OYPT92HJtrXgHIPJAM5kmRn8JR11lAccCAQCKx73X40WGhzKfZ7/XEW4F5JRQhbh4mGEi/ycPuU+CF4dcINUZL9LDiJaBz3SfvHwvSqPnV+nR1+TOFgQVnPirgxSX1Vtb86rKAPHkKdnZSqd2jMVVYKFmqW8hkRA04CA+YKXmcACsEXoyhyvbdUuoedlmg0JDoFjcj4tcyNdyzc4IGy5tm43e5E5IqdgECMqrq7jZAyQp0yFV/HJI8725eD2rkS0olh8thKbVMprGBvMikwHT+R3QTZu6FEObYLxmNCkCazVG6zpOe0lVXn3+nBppj31s9sMVlAe+gQA7hpIEsXetcrw883Pj6H1UHjAR8+EyVCdtZ9kguG+W6a7G+vtKd8amAGFbD1ofrxmCQeSu8KhDlo0Rn9o+rX2viuqcQXsca7iYNKkQ64CUg+vrq3iizonOduR7IvvqSvP6SG5wbGeB7h28532S/cGJr1KPKmzf2a/0uxmpfgaDTsYr9z9k5fG9kui2n7c9k=
