sudo: false
language: javascript
install: true
branches:
  only:
  - master
before_script: make travis-init
script: make travis
deploy:
  provider: script
  script: git clone https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG;
    cd $TRAVIS_REPO_SLUG; make travis-deploy
  on:
    branch: master
