gitRepo: ArcBlock/forge-js
srcPath: docs/src
categories:
  packages:
    basePath: /packages
    title: Reference
    link: /
    priority: 999
    sidebar:
      'null':
        - /
      'Forge Core':
        links:
          - /forge-sdk
          - /graphql-client
          - /grpc-client
          - /forge-wallet
          - /mcrypto
          - /forge-util
          - /forge-message
          - /forge-proto
      'DID Auth':
        links:
          - /did
          - /did-auth
          - /did-util
          - /did-auth-storage
          - /did-auth-storage-mongo
          - /did-auth-storage-keystone
          - /did-auth-storage-firebase
      'Atomic Swap':
        links:
          - /swap-storage
          - /swap-storage-mongo
          - /swap-retriever
          - /did-auth
      'Misc':
        links:
          - /forge-config
          - /tx-util
