// Generate by [js2dts@0.3.3](https://github.com/whxaxes/js2dts#readme)

import { EventEmitter } from 'events';
declare class SwapStorage extends EventEmitter {
  payloadFields: string[];
  /**
   * Creates an instance of SwapStorage.
   *
   * @class
   * @param {object} options
   */
  constructor(options: any);
  create(params: any): void;
  read(traceId: any): void;
  update(traceId: any, updates: any): void;
  finalize(traceId: any, payload: any): void;
  listByStatus(status: any): void;
  listByOfferAddress(address: any, status: any): void;
  listByDemandAddress(address: any, status: any): void;
  delete(traceId: any): void;
  exist(traceId: any): void;
}
declare class MongoSwapStorage extends SwapStorage {
  collectionName: string;
  options: _Lib.T100;
  /**
   * Creates an instance of MongoSwapStorage.
   *
   * @class
   * @param {Object} options { collection, url }
   * @param {string} options.url - mongodb connection string
   * @param {string} [options.collection='abt_forge_swaps'] - which collection to store the swap records
   */
  constructor(options: _Lib.T100);
  connectionFailed(err: any): void;
  handleNewConnectionAsync(client: any): void;
  changeState(newState: any): void;
  setCollection(collection: any): this;
  collectionReady(): any;
  /**
   * Get an atomic-swap order by traceId
   *
   * @method
   * @param {string} traceId - the uuid of the swap order
   * @returns {object} the atomic-swap-order
   * @memberof MongoSwapStorage
   */
  read(traceId: string): any;
  /**
   * Create new atomic-swap order, traceId should be generated by user
   *
   * @method
   * @param {string} traceId
   * @param {object} attributes
   * @returns {Promise<object>}
   * @memberof MongoSwapStorage
   */
  create(traceId: string, attributes: any): Promise<any>;
  /**
   * Finalize the payload of atomic-swap
   *
   * @method
   * @param {string} traceId
   * @param {object} payload
   * @returns {Promise<object>}
   * @memberof MongoSwapStorage
   */
  finalize(traceId: string, payload: any): Promise<any>;
  /**
   * Update the status of an atomic-swap order, will not allow payload fields to be updated
   *
   * @method
   * @param {string} traceId
   * @param {object} updates
   * @returns {Promise<object>}
   * @memberof MongoSwapStorage
   */
  update(traceId: string, updates: any): Promise<any>;
  /**
   * Delete atomic swap order by traceId
   *
   * @method
   * @param {string} traceId
   * @returns void
   * @memberof MongoSwapStorage
   */
  delete(traceId: string): any;
  /**
   * Check if atomic swap record exists
   *
   * @method
   * @param {string} traceId
   * @returns {Boolean}
   * @memberof MongoSwapStorage
   */
  exist(traceId: string): boolean;
  /**
   * Find atomic swap records by status
   *
   * @method
   * @param {string} status - check out list of supported status here
   * @returns {Promise<Array>}
   * @memberof MongoSwapStorage
   * TODO: add pagination for this
   */
  listByStatus(status: string): Promise<any[]>;
  /**
   * Find atomic swap records by offer address and status
   *
   * @method
   * @param {string} address
   * @param {string} [status='']
   * @returns {Promise<Array>}
   * @memberof MongoSwapStorage
   * TODO: add pagination for this
   */
  listByOfferAddress(address: string, status?: string): Promise<any[]>;
  /**
   * Find atomic swap records by demand address and status
   *
   * @method
   * @param {string} address
   * @param {string} [status='']
   * @returns {Promise<Array>}
   * @memberof MongoSwapStorage
   * TODO: add pagination for this
   */
  listByDemandAddress(address: string, status?: string): Promise<any[]>;
  close(): void;
}
declare const _Lib: typeof MongoSwapStorage;
declare namespace _Lib {
  export interface T100 {
    url: string;
    collection?: string;
  }
}
export = _Lib;
