[app]
name = "forge_kvstore_nodejs"
version = "0.1.0"

path = "/Users/wangshijun/Develop/arcblock/forge-js/examples/kvstore"
executable = "app.js"
logfile = "logs/app.log"
sock_tcp = "tcp://127.0.0.1:9528"

[forge]
decimal = 16
proto_version = 1
path = "/tmp/.forge_kvstore_nodejs/core"
# State db path
db = "data"
# index db path
index_db = "index"
keystore = "keystore"
logfile = "logs/forge.log"

sock_grpc = "tcp://127.0.0.1:28210"

consensus_engine = "tendermint"
storage_engine = "ipfs"
hash = "sha3"
encoding = "base64"
unlock_ttl = 300

[forge.limit]
# max grace period is 10
grace_peroid = 10

[forge.account]
# for ethereum compatibility, use secp256k1
public_key_format = "ed25519"
# for ethereum compatibility, use keccak_256
public_key_hash_format = "sha3_256"
# for ethereum compatibility, use base16
address_format = "base58"

[forge.transaction]
disabled_tx = ["SysUpgradeTx"]

[forge.web]
enabled = false

[tendermint]
version = "0.27.3-01"
moniker = "forge"
path = "/tmp/.forge_kvstore_nodejs/tendermint"
# relative paths to "path"
logfile = "logs/tendermint.log"

# socket to proxy app
sock_proxy_app = "unix://socks/tm_proxy_app.sock"

# socket for tendermint json rpc
sock_rpc = "unix://socks/tm_rpc.sock"

# socket for tendermint grpc (right now just use it for send tx and commit immediately)
sock_grpc = "unix://socks/tm_grpc.sock"

# socket for tendermint p2p. Normally this shall be opened to the public network
sock_p2p = "tcp://0.0.0.0:26656"

# socket for performance metrics
sock_prof = ""

# persistent peers
persistent_peers = ""

# seed peers
seed_peers = ""

# timeout for commiting a new block
timeout_commit = "100ms"

# create empty blocks in 5s interval
create_empty_blocks = true


[tendermint.genesis]
genesis_time = "2018-11-05T19:22:08.938749Z"
chain_id = 1
max_bytes = 22020096
max_gas = -1
app_hash = ""

# note that if you don't give this information we will use self as validator
# Please do not remove this section if its empty
[[tendermint.genesis.validators]]

[ipfs]
version = "0.4.18"
path = "/tmp/.forge_kvstore_nodejs/ipfs"
logfile = "logs/ipfs.log"
storage_max = "10GB"
bootstrap = []

#ipfs_cluster_version = "0.7.0"
#ipfs_cluster_ctl_version = "0.7.0"

"max_file_size.admin" = "100M"
"max_file_size.account" = "1M"
