[app]
name = "forge_kvstore_nodejs"
version = "0.1.0"
app_hash = "1234"

path = "/Users/wangshijun/Develop/arcblock/forge-js/examples/kvstore"
# executable = "nodemon --exitcrash --spawn --config nodemon.json"
executable = "server.js"
sock_tcp = "tcp://127.0.0.1:9528"

[forge]
decimal = 16
proto_version = 1
path = "~/.forge_kvstore_nodejs/core"
sock_grpc = "tcp://127.0.0.1:28210"

pub_sub_key = "ABTTOTHEMOON"

[forge.stake]

[forge.stake.timeout]
# for general stake, we do 10s
general = 10
# for node stake, we do 60s
stake_for_node = 60

[forge.web]
enabled = true

[tendermint]
moniker = "forge"
path = "~/.forge_kvstore_nodejs/tendermint"

# socket to proxy app
sock_proxy_app = "tcp://127.0.0.1:28220"

# socket for tendermint json rpc
sock_rpc = "tcp://127.0.0.1:28221"

# socket for tendermint grpc (right now just use it for send tx and commit immediately)
sock_grpc = "tcp://127.0.0.1:28222"

# socket for tendermint p2p. Normally this shall be opened to the public network
sock_p2p = "tcp://0.0.0.0:26656"

# socket for performance metrics
sock_prof = ""

# persistent peers
persistent_peers = ""

# seed peers
seed_peers = ""

# timeout for commiting a new block
timeout_commit = "5s"

# create empty blocks in 5s interval
create_empty_blocks = false

# set if this node runs in a seed mode
seed_mode = false

[tendermint.genesis]
genesis_time = "2018-11-05T19:22:08.938749Z"
chain_id = "forge"
max_bytes = 22020096
max_gas = -1
app_hash = ""

# note that if you don't give this information we will use self as validator
[[tendermint.genesis.validators]]
# address = "D875CBC0F1D0925D62AB235F1DA909D89CDF9D78"
# name = "forge_genesis_validator"
# power = "10"

# [tendermint.genesis.validators.pub_key]
# type = "tendermint/PubKeyEd25519"
# value = "whsJQCA4g4bzQeaBe69/ZW/xHRNPAI2QxHV4CIgguq4="

[ipfs]
version = "0.4.18"
path = "~/.forge_kvstore_nodejs/ipfs"
