const Mcrypto = require('@arcblock/mcrypto');
const { fromRandom, WalletType } = require('@arcblock/forge-wallet');
const { jwtDecode, jwtVerify } = require('@arcblock/abt-did');

const type = WalletType({
  role: Mcrypto.types.RoleType.ROLE_APPLICATION,
  pk: Mcrypto.types.KeyType.ED25519,
  hash: Mcrypto.types.HashType.SHA3,
});

const wallet = fromRandom(type);
console.log(wallet.toJSON());

console.log(
  jwtDecode(
    'eyJhbGciOiJFZDI1NTE5IiwidHlwIjoiSldUIn0.eyJhY3Rpb24iOiJyZXNwb25zZUF1dGgiLCJhcHBJbmZvIjp7ImNoYWluSG9zdCI6Imh0dHA6Ly8xNTkuNjUuMTM4Ljc1OjgyMTAvYXBpLyIsImNoYWluSWQiOiJmb3JnZSIsImNoYWluVG9rZW4iOiJUQkEiLCJjb3B5cmlnaHQiOiJodHRwczovL2V4YW1wbGUtYXBwbGljYXRpb24vY29weXJpZ2h0IiwiZGVjaW1hbHMiOjE2LCJkZXNjcmlwdGlvbiI6IkEgc2ltcGxlIHdvcmtzaG9wIGZvciBkZXZlbG9wZXJzIHRvIHF1aWNrbHkgZGV2ZWxvcCwgZGVzaWduIGFuZCBkZWJ1ZyB0aGUgRElEIGZsb3cuIiwiaWNvbiI6Ii9pbWFnZXMvbG9nb0AyeC5wbmciLCJuYW1lIjoiQUJUIERJRCBXb3Jrc2hvcCIsInBhdGgiOiJodHRwczovL2FyY3dhbGxldC5pby9pLyIsInB1Ymxpc2hlciI6ImRpZDphYnQ6ek5LU0hESzVLVFo1YmR4ZkhvS3A2RjJpaWJicExyaVlKRFNpIiwic3VidGl0bGUiOiJQbGF5IHdpdGggRElEIGF1dGhlbnRpY2F0aW9uIHByb3RvY29sLiJ9LCJyZXF1ZXN0ZWRDbGFpbXMiOlt7Iml0ZW1zIjpbImVtYWlsIiwicGhvbmUiXSwibWV0YSI6eyJkZXNjcmlwdGlvbiI6IlBsZWFzZSBwcm92aWRlIHlvdXIgcHJvZmlsZSBpbmZvcm1hdGlvbi4ifSwidHlwZSI6InByb2ZpbGUifSx7Imhhc2giOnsiZGlnZXN0IjoiejczakM3Rm9KTVNwbUx3c3JXRjdvVDV4QkdZYU1STnJXczdhakJFQjJ2dUpoIiwibWV0aG9kIjoic2hhMjU2In0sIm1ldGEiOnsiZGVzY3JpcHRpb24iOiJEYXRhIHBvbGljeSIsImlkIjoiMSJ9LCJ0eXBlIjoiYWdyZWVtZW50IiwidXJpIjoiaHR0cDovLzE1OS42NS4xMzguNzU6NDAwMC9hcGkvYWdyZWVtZW50LzEifSx7Imhhc2giOnsiZGlnZXN0IjoiejYyYWNkQjhySzVrcFVhcm5QaURmQm5FSHhjanB1d2hOdDFCZEFVWURhZU41IiwibWV0aG9kIjoic2hhMyJ9LCJtZXRhIjp7ImRlc2NyaXB0aW9uIjoiVGVybXMgb2YgU2VydmljZSIsImlkIjoiMiJ9LCJ0eXBlIjoiYWdyZWVtZW50IiwidXJpIjoiaHR0cDovLzE1OS42NS4xMzguNzU6NDAwMC9hcGkvYWdyZWVtZW50LzIifV0sInVybCI6Imh0dHA6Ly8xNTkuNjUuMTM4Ljc1OjQwMDAvYXBpL2F1dGgvIiwiZXhwIjoiMTU1MzE2MTkxMSIsImlhdCI6IjE1NTMxNjAxMTEiLCJpc3MiOiJkaWQ6YWJ0OnoxMUZFUGdSNGJuMTFtdmtEdUFRUjV4bWFDZGJ5Q3RIZEM2ZiIsIm5iZiI6IjE1NTMxNjAxMTEifQ.GvxWsv3wZmyDnk3_ZuTClnaqxkelSF1j1Czutl9mcocX0ehN2fnyqNg5glseNY8oMasaSA6Aqrboff07A4miB'
  )
);
